apiVersion: v1
kind: Pod
metadata:
  name: db-checker
spec:
  restartPolicy: Never
  containers:
  - name: mysql-client
    image: mysql:5.7
    # This command tries to connect and print the server status
    command: ["sh", "-c", "mysql -h $DB_HOST -u $DB_USER -p$DB_PASS -e 'STATUS;'"]
    env:
      - name: DB_USER
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: username
      - name: DB_PASS
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: password
      - name: DB_HOST
        valueFrom:
          secretKeyRef:
            name: db-credentials
            key: host